<a href="https://colab.research.google.com/github/lokeshkumarn/Notebooks/blob/master/ComputerVision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from  matplotlib import pyplot as plt

In [4]:
rand_img = np.random.uniform(0,3,size=(5,5))
rand_img

array([[2.44535659, 1.21208794, 1.84952648, 1.88433914, 0.5966908 ],
       [0.95863786, 0.803343  , 2.75497213, 0.71573458, 1.8422587 ],
       [2.68622104, 1.71695723, 2.67901332, 1.65825594, 2.74298159],
       [2.16986662, 0.52114449, 2.67473792, 1.97988724, 2.25840741],
       [2.98574197, 1.1117791 , 0.56573239, 2.50392066, 0.01296098]])

In [5]:
rand_img = np.uint32(rand_img)
rand_img

array([[2, 1, 1, 1, 0],
       [0, 0, 2, 0, 1],
       [2, 1, 2, 1, 2],
       [2, 0, 2, 1, 2],
       [2, 1, 0, 2, 0]], dtype=uint32)

In [8]:
hist=np.histogram(rand_img,bins=4)
hist

(array([ 7,  0,  8, 10]), array([0. , 0.5, 1. , 1.5, 2. ]))